### ISSUE TITLE
[e] SC 1.2.2 scene 5 audio script

### ISSUE THREAD

**Issue by jade-mc** [w3c/wai-wcag-videos#13]
Suggest inserting 'or mixed up' after 'garbled' to make clearer.

**Comment by nitedog** [comment]
Following issue #2 the word "garbled" was changed to "inaccurate" - is that clear enough now?

**Comment by jade-mc** [comment]
Hiya, I'm not sure inaccurate has the same meaning as garbled, or perhaps both are needed? 'Because of all the technical jargon which isn't recognised, the automatic captioning becomes garbled or mixed up, which makes it inaccurate.' But maybe I'm overthinking it.

**Comment by bakkenb** [comment]
Yes, I believe that Jade is correct here. I said to change it to inaccurate, but she is correct that inaccurate has a very different meaning than garbled. I didn't think about that. I like the direction she is going with this sentence much better.

**Comment by nitedog** [comment]
This is quite a lengthy and complex sentence. Do you both feel we need this distinction between "garbled", "mixed up", and "inaccurate" or is the point sufficiently made?

**Comment by jade-mc** [comment]
Just get rid of garbled then, it's a low frequency word which will be difficult to understand if English isn't a first language. _Because of all the technical jargon which isn't recognised, the automatic captioning becomes mixed up, which makes it incorrect._ Also changed inaccurate to incorrect (basing my decisions on the language level indicated in English Vocab Profile [https://www.englishprofile.org/wordlists/evp](url) by the way.)

**Comment by bakkenb** [comment]
Okay, going back on what I said earlier. I would like to restate my preference for...

> And automatic captioning is often inaccurate because of all the technical jargon it doesn’t recognize.

The reason is that it is simple and straight forward (these audio lines have to be very simple to follow along with the video easily), and because I am thinking that the word "inaccurate" is actually right. 

When AI cannot figure out a jargon word or other words because of a dialect, it will give it it's best shot and fill in with actual words. It usually will not add just a jumble of letters that is "garbled," it will add words that sound extremely similar to the audio, but aren't. Therefore the captioning is inaccurate.  Here is an [article from a leading captioning company in the US](https://www.3playmedia.com/blog/artificial-intelligence-is-good-but-is-it-good-enough-for-captions/) (jump to the "ASR for Captioning" heading for some good examples).

**Comment by nitedog** [comment]
Seems we've gone full circle and there is now agreement to keep this sentence as-is. Please re-open issue if you have concerns.

**Comment by jade-mc** [comment]
Hiya, if I comment does it re-open the issue? The sentence isn't the original btw, garbled will need to be changed to inaccurate/incorrect.

**Comment by nitedog** [comment]
You are right, not the initial sentence but changed to "inaccurate"; see [SC 1.2.2 script](https://wai-wcag-videos.netlify.app/sc-1.2.2/).

And you need to select the "Reopen and comment" button beside the default "Comment" button to reopen the issue.
