### ISSUE TITLE
[e] SC 2.3.1 script, scene 4 audio

### ISSUE THREAD

**Issue by jade-mc** [w3c/wai-wcag-videos#35]
Original: Fortunately that flickering pattern was below the so called “general flash” and “red flash” thresholds, so that her migranes were not triggered by the animation.

Suggest: Fortunately that flickering pattern was below the “general flash” and “red flash” thresholds, so the animation didn't trigger a migraine. The thresholds give the acceptable limits for the number and types of flashes which can occur in a particular time or area.

**Comment by nitedog** [comment]
1. Can we change the first sentence to: `Fortunately that flickering pattern was below the “general flash” and “red flash” thresholds, so the animation didn't trigger _her_ migraine` or `Fortunately that flickering pattern was below the “general flash” and “red flash” thresholds, so the animation didn't trigger a migraine _for her_` -- that is, make it specific to Manti because it may actually still trigger reactions for people with more sensitivity
2. Is the second sentence necessary? I'm a little torn about this. It is fairly short and well explained but I still wonder if it is worth the duration?

**Comment by nitedog** [comment]
Sub-group discussion on 2 April 2021:

> She uses a fairly large computer screen so sometimes videos and animations could have flashing that cause her painful migranes.
> One day she was using a website that she hadn’t used before, and was surprized by flashing animations on the website.
> Fortunately this flashing animation was below the “general flash” and “red flash” thresholds. These thresholds set the limits for the number and types of flashes which can occur in a particular time or area. Therefore this animation did not trigger her migraine.
