### ISSUE TITLE
[e] All scripts - remove unnecessary persona details

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-wcag-videos#39]
For example, these types of persona details:

> Martine is 62 years old and has been hard of hearing since birth. She can hear some sounds, but not enough to understand speech.

This comes from "How People with Disabilities Use the Web". Repeating it here is:

1. Repetitive: Martine may be featured several times, and hearing that every time is not useful
2. Dependent: If the persona for Martine changes, all related scripts would be impacted

Suggestion: remove all non-essential details. In this case, for example, "62 years old" and "hard of hearing *since birth*" seem irrelevant to this particular requirement/script.

**Comment by bakkenb** [comment]
So would the script be left with...

> Martine can hear some sounds, but not enough to understand speech.

I think it still works.

**Comment by nitedog** [comment]
@jade-mc @bakkenb please check the 7 script updates referenced before this comment.

**Comment by bakkenb** [comment]
I finished looking at these 7 scripts. I added comments directly in the commits.

**Comment by nitedog** [comment]
@jade-mc and @bakkenb, in addition to the above 7 scripts, can you please also take a quick look at the following 9 scripts and make sure you are comfortable with the amount of personal information being provided (ie. only what is essential to frame the persona and scenario):

- [SC 2.2.5](https://wai-wcag-videos.netlify.app/sc-2.2.5/)
- [SC 2.3.3](https://wai-wcag-videos.netlify.app/sc-2.3.3/)
- [SC 1.3.6](https://wai-wcag-videos.netlify.app/sc-1.3.6/)
- [SC 2.1.1](https://wai-wcag-videos.netlify.app/sc-2.1.1/)
- [SC 2.1.2](https://wai-wcag-videos.netlify.app/sc-2.1.2/)
- [SC 2.1.3](https://wai-wcag-videos.netlify.app/sc-2.1.3/)
- [SC 2.1.4](https://wai-wcag-videos.netlify.app/sc-2.1.4/)
- [SC 2.3.1](https://wai-wcag-videos.netlify.app/sc-2.3.1/)
- [SC 2.3.2](https://wai-wcag-videos.netlify.app/sc-2.3.2/)

**Comment by bakkenb** [comment]
Comments on reviewing the above 9 scripts for personal information present or missing...

- 2.2.5: Seems fine to me, no additional personal information needed.
- 2.3.3: Seems fine to me, no additional personal information needed.
- 1.3.6: If we see Xeena reading a school book it wouldn't hurt to let the audience know that verbally by saying something like, "Xeena, a first year university student, has a language processing disability." (ED - Medium)
- 2.1.1: Seems fine to me, no additional personal information needed.
- 2.1.2: Seems fine to me, no additional personal information needed.
- 2.1.3: Maybe this one could benefit for having a personal reason for needing to work with digital shapes. Drawing shapes.
- 2.1.4: This one needs more info in Scene one audio so that we understand what the "article" could be in scene 2. Is it a new article, and journal article, a school work article. I thought Alex was a journalist at one point.
- 2.3.1: Seems fine to me, no additional personal information needed.
- 2.3.2: Could suggest Manti is a teenager, but not an issue at all to leave as is.

**Comment by jade-mc** [comment]
I've looked at these by the way, nothing to add to Brent's comments, agree with them all. 
Only thing is a discrepancy in 2.1.3 between Braimi/Niando in the notes and scipt.
